### ISSUE TITLE
Any objection to adding the `attribute_name` to the errors raised when types don't match?

### ISSUE THREAD

**Issue by juanpaco** [eventide-project/schema#11]
Specifically here: https://github.com/eventide-project/schema/blob/master/lib/schema/schema.rb#L53

I'm trying to import data from a 3rd-party system that has a lot of attributes that could have raised an error that I'm getting.  An example error:

` Error raised (Error Class: Schema::Attribute::TypeError, Error Message: <non-integer number redacted> is not a kind of Integer`

This is a proposal to augment the error with something like the following:

` Error raised (Error Class: Schema::Attribute::TypeError, Error Message: Attribute <attribute_name> with value <non-integer number redacted> is not a kind of Integer`

Hopefully the use case of importing from the 3rd-party doesn't render this too special of a case.

I'm happy to submit a PR for this if this change is acceptable.

**Comment by sbellware** [comment]
@juanpaco I can't believe how far behind we got on this. Sorry. 

The Schema library now type issues of the form:
```
"#{val.inspect} of type #{val.class.name} cannot be assigned to attribute #{attribute_name} of type Boolean (Strict: #{strict.inspect})"
```

The implementation is independent of your PR. Sorry for losing track of it. Hopefully, your need is addressed with the most recent release.
