### ISSUE TITLE
Setting an attribute with a default to nil causes the value to be the default value

### ISSUE THREAD

**Issue by sbellware** [eventide-project/schema#3]
Need an attribute state that allows the differentiation between "unset" and nil

**Comment by sbellware** [comment]
There's an example in @ntl's testbench library of doing this with `instance_variable_defined`:
https://github.com/ntl/test-bench/blob/master/lib/test_bench/output.rb#L87-L95

**Comment by ntl** [comment]
An updated link to the example: https://github.com/ntl/test-bench/blob/master/lib/test_bench/output.rb#L98-L102

**Comment by sbellware** [comment]
The change had greater impact on the attribute library, but once that change was done, tests were added to schema, and the version number increased to indicate breaking changes.
