### ISSUE TITLE
The attributes methods should optionally return superclass attributes

### ISSUE THREAD

**Issue by sbellware** [eventide-project/schema#4]
`attributes` and `attribute_names` methods take an `ancestors` keyword argument.

Class interface default: `ancestors: false`
Instance interface default:  `ancestors: true`

**Comment by sbellware** [comment]
Enumerate the ancestors list. Gather attributes for any classes that are data structures.

This could impact the performance of converting a schema to a hash. The best default might be to only return the attributes of a single class in the hierarchy.

**Comment by sbellware** [comment]
@ntl Do you know of a concrete example where we wanted this? It would involve having schema classes inheriting from other schema classes. I'm not sure that schemas inheriting from other schemas would be a good thing to encourage, design wise. Then again, the language allows for it, and not doing it would be surprising to the uninitiated. Then again, "prefer composition rather than inheritance" would be surprising to many. So, should we try to do everything the language does, or limit the things that can be done with this library to the things that reflect more essential principles, like avoiding inheritance where possible (especially when it's being used for reuse rather than for creating substitutability, and especially where data structures are concerned).

**Comment by ntl** [comment]
You described the rationale behind this pretty well.

I believe you had brought about the only concrete example in the wild, where you had multiple message schemas using inheritance to share common attributes.

To me, this is a questionable feature. It's only benefit is the principle of least surprise. There is no known real world reason to use class inheritance instead of modules to share attributes.

**Comment by sbellware** [comment]
I'm on the same page in regards to using modules if the goal is reuse. This is effectively a feature that flirts with encouraging an anti pattern. Thanks!
